# Generated by Django 3.2.9 on 2021-11-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='science_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
